application: talpais16
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.bin)
  static_files: static/\1
  upload: static/(.*\.bin)

- url: /(.*\.ttf)
  static_files: static/\1
  upload: static/(.*\.ttf)

- url: /(.*\.woff)
  static_files: static/\1
  upload: static/(.*\.woff)

- url: /(.*\.woff2)
  static_files: static/\1
  upload: static/(.*\.woff2)

- url: /(.*\.jpg)
  static_files: static/\1
  upload: static/(.*\.jpg)

- url: /(.*\.svg)
  static_files: static/\1
  upload: static/(.*\.svg)

- url: /(.*\.css)
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest